flowchart TD
    %% Actores
    P([Paciente])
    M([Médico])
    A([Administrador])
    R([Recepción/Cajero])
    S([Sistema / Motor IA])

    subgraph M1_M2 [1-2: Autenticación y Perfil]
        UC_Auth(Iniciar Sesión y 2FA)
        UC_Hist(Descargar Historial)
    end

    subgraph M3_M4 [3-4: Staff, Catálogos y Admin]
        UC_Dir(Buscar Médico)
        UC_Crud(CRUD Sedes/Consultorios)
        UC_Forzar(Forzar Asignaciones y Excepciones)
    end

    subgraph M5_M6 [5-6: Lógica de Negocio y Horarios]
        UC_Triaje(Validar Triaje y Urgencia)
        UC_Slot(Generar Bloques y Prevenir Solapamiento)
    end

    subgraph M7_M8 [7-8: Citas y Lista de Espera]
        UC_Repro(Reprogramar Cita)
        UC_Bloq(Bloquear por Límite de Cambios)
        UC_Asist(Registrar Asistencia en Recepción)
        UC_Esp(Ordenar Cola y Asignar desde Lista)
    end

    P --> UC_Auth
    P --> UC_Hist
    P --> UC_Dir
    P --> UC_Repro

    M --> UC_Dir

    A --> UC_Crud
    A --> UC_Forzar

    R --> UC_Asist

    S --> UC_Triaje
    S --> UC_Slot
    S --> UC_Bloq
    S --> UC_Esp

    UC_Repro -. include .-> UC_Bloq
    UC_Triaje -. triggers .-> UC_Slot
    UC_Esp -. updates .-> UC_Slot
