flowchart LR
    %% Actores
    P([Paciente])
    M([Médico])
    A([Administrador])
    S([Sistema / IA])

    %% Casos de Uso
    P --> UC1(Completar Formulario de Triaje)
    P --> UC2(Confirmar/Cancelar Cita)
    P --> UC3(Gestionar Perfil)
    
    S --> UC4(Interpretar Triaje y Calcular Urgencia)
    S --> UC5(Procesar Bolsa Batch)
    S --> UC6(Asignar Smart Slots)
    S --> UC7(Enviar Notificaciones)
    
    M --> UC8(Visualizar Agenda)
    M --> UC9(Ver Resumen Triaje)
    
    A --> UC10(Gestionar Directorio)
    A --> UC11(Monitorear Sistema)
    
    UC1 -. include .-> UC4
    UC5 -. include .-> UC6
