@startuml
left to right direction

skinparam shadowing false
skinparam actor {
  BackgroundColor #F4F6F7
  BorderColor #2C3E50
  FontColor #2C3E50
}
skinparam usecase {
  BackgroundColor #EBF5FB
  BorderColor #2980B9
  FontColor #154360
  ArrowColor #2980B9
}
skinparam arrow {
  Color #34495E
  Thickness 1.5
}
skinparam package {
  BackgroundColor #FDEDEC
  BorderColor #C0392B
  FontColor #922B21
}


actor "Paciente" as Pac

package "MÓDULO 2: Pacientes" {
  usecase "Registrar paciente" as UC1
  usecase "Gestionar perfil" as UC2
  usecase "Mostrar dashboard" as UC3
  usecase "Descargar documentos" as UC4
  usecase "Ver historial de citas" as UC5
}

Pac -[#27AE60]-> UC1
Pac -[#27AE60]-> UC2
Pac -[#27AE60]-> UC3
Pac -[#27AE60]-> UC4
Pac -[#27AE60]-> UC5
@enduml