@startuml
left to right direction

skinparam shadowing false
skinparam actor {
  BackgroundColor #F4F6F7
  BorderColor #2C3E50
  FontColor #2C3E50
}
skinparam usecase {
  BackgroundColor #EBF5FB
  BorderColor #2980B9
  FontColor #154360
  ArrowColor #2980B9
}
skinparam arrow {
  Color #34495E
  Thickness 1.5
}
skinparam package {
  BackgroundColor #FDEDEC
  BorderColor #C0392B
  FontColor #922B21
}


actor "Admin" as Adm
actor "Sistema" as Sis

package "MÓDULO 6: Horarios y disponibilidad" {
  usecase "Creación de slot de tiempo en bloques" as UC1
  usecase "Aplicar políticas de reserva" as UC2
  usecase "Sugerir alternativas" as UC3
  usecase "Modificar la disponibilidad de horarios" as UC4
}

Sis -[#E74C3C]-> UC1
Sis -[#E74C3C]-> UC2
Sis -[#E74C3C]-> UC3

Adm -[#8E44AD]-> UC1
Adm -[#8E44AD]-> UC4
@enduml